CREATE DATABASE IF NOT EXISTS db_industria_alimenticia CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE db_industria_alimenticia;

DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  descricao TEXT NOT NULL,
  setor VARCHAR(100) NOT NULL,
  prioridade ENUM('baixa','media','alta') NOT NULL DEFAULT 'baixa',
  data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('a fazer','fazendo','pronto') NOT NULL DEFAULT 'a fazer',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
